// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oql.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import oql.implementation.OQL;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * This action executes an OQL query and returns the amount of results
 * 
 * For further documentation please refer to https://docs.mendix.com/appstore/modules/oql-module#countrowsoqlstatement
 */
public class CountRowsOQLStatement extends UserAction<java.lang.Long>
{
	private final java.lang.String statement;
	private final java.lang.Long amount;
	private final java.lang.Long offset;

	public CountRowsOQLStatement(
		IContext context,
		java.lang.String _statement,
		java.lang.Long _amount,
		java.lang.Long _offset
	)
	{
		super(context);
		this.statement = _statement;
		this.amount = _amount;
		this.offset = _offset;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext context = getContext().createSudoClone();

		Long result = OQL.countRowsOQL(context, statement, amount);
		
		OQL.resetParameters();
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CountRowsOQLStatement";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
