// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oql.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import oql.implementation.OQL;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * This action executes an OQL query and returns the count of rows that would be returned.
 * 
 * It is useful to run a query without the overhead of generating Mendix objects for the result in cases where those are not needed.
 * 
 * Only SELECT queries are supported.
 * Queries are executed in a sudo clone of the existing context, so no access rules are applied.
 * Named parameter values can be defined by first calling the appropriate add parameter functions. They will all be cleared after the query is executed.
 * 
 * For details of supported OQL syntax and feature, see https://docs.mendix.com/refguide/oql/
 * 
 * This action takes the following parameters:
 * - statement: OQL Query to be executed.
 * - amount: Limits the number of results to at most this amount. If there are more results in the query, this amount is returned.
 * - offset: This parameter is ignored and might be removed in a future version.
 * 
 */
public class CountRowsOQLStatement extends UserAction<java.lang.Long>
{
	private final java.lang.String statement;
	private final java.lang.Long amount;
	private final java.lang.Long offset;

	public CountRowsOQLStatement(
		IContext context,
		java.lang.String _statement,
		java.lang.Long _amount,
		java.lang.Long _offset
	)
	{
		super(context);
		this.statement = _statement;
		this.amount = _amount;
		this.offset = _offset;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext context = getContext().createSudoClone();

		Long result = OQL.countRowsOQL(context, statement, amount);
		
		OQL.resetParameters();
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CountRowsOQLStatement";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
