// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oql.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * This action executes a DML statement and returns number of affected rows
 * 
 * For further documentation please refer to https://docs.mendix.com/appstore/modules/oql-module#executedmlstatement
 */
public class ExecuteDMLStatement extends UserAction<java.lang.Long>
{
	private final java.lang.String statement;

	public ExecuteDMLStatement(
		IContext context,
		java.lang.String _statement
	)
	{
		super(context);
		this.statement = _statement;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ExecuteDMLStatement";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
