// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oql.actions;

import java.util.List;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import oql.implementation.OQL;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * This action executes an OQL query and returns a list of Mendix objects.
 * 
 * Only SELECT queries are supported.
 * Queries are executed in a sudo clone of the existing context, so no access rules are applied.
 * Named parameter values can be defined by first calling the appropriate add parameter functions.
 * 
 * For details of supported OQL syntax and feature, see https://docs.mendix.com/refguide/oql/
 * 
 * This action takes the following parameters:
 * - statement: OQL Query or fully qualified name of a Dataset (module and Dataset name) to be executed.
 * - returnEntity: Name of the entity type to be used to store results.
 * - amount: If set, will limit the number of results to at most this amount. It is recommended to use an explicit sorting order in the statement parameter when using amount.
 * - offset: If set, will offset the results of the query by this quantity. It is recommended to use an explicit sorting order in the statement parameter when using offset.
 * - preserveParameters: If false, all parameters defined for this query will be cleared.
 */
public class ExecuteOQLStatement extends UserAction<java.util.List<IMendixObject>>
{
	private final java.lang.String statement;
	private final java.lang.String returnEntity;
	private final java.lang.Long amount;
	private final java.lang.Long offset;
	private final java.lang.Boolean preserveParameters;

	public ExecuteOQLStatement(
		IContext context,
		java.lang.String _statement,
		java.lang.String _returnEntity,
		java.lang.Long _amount,
		java.lang.Long _offset,
		java.lang.Boolean _preserveParameters
	)
	{
		super(context);
		this.statement = _statement;
		this.returnEntity = _returnEntity;
		this.amount = _amount;
		this.offset = _offset;
		this.preserveParameters = _preserveParameters;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext context = getContext().createSudoClone();

		List<IMendixObject> result = OQL.executeOQL(context, statement, returnEntity, amount, offset);
		
		if (!this.preserveParameters) 
			OQL.resetParameters();
		
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ExecuteOQLStatement";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
