// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oql.actions;

import java.io.OutputStreamWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.Map.Entry;
import java.util.Optional;
import java.util.stream.Collectors;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.connectionbus.data.IDataColumnSchema;
import com.mendix.systemwideinterfaces.connectionbus.data.IDataTable;
import com.mendix.systemwideinterfaces.connectionbus.requests.IParameterMap;
import com.mendix.systemwideinterfaces.connectionbus.requests.IRetrievalSchema;
import com.mendix.systemwideinterfaces.connectionbus.requests.types.IOQLTextGetRequest;
import com.mendix.systemwideinterfaces.core.IContext;
import oql.implementation.MxCSVWriter;
import oql.implementation.OQL;
import java.io.*;
import java.util.Collections;
import com.mendix.webui.CustomJavaAction;

/**
 * Java action that executes an OQL query and returns the result as a formatted markdown table.
 */
public class ExportOQLToMarkdown extends CustomJavaAction<java.lang.String>
{
	private java.lang.String query;

	public ExportOQLToMarkdown(IContext context, java.lang.String query)
	{
		super(context);
		this.query = query;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		final int PAGE_SIZE = 10000;

		try (ByteArrayOutputStream os = new ByteArrayOutputStream();
			MxCSVWriter writer = new MxCSVWriter(new OutputStreamWriter(os), '|', Optional.empty(), Optional.empty(), Optional.of('|'), Optional.of('|'), true)) {

			int offset = 0;
			while (true) {

				IContext context = getContext().createSudoClone();
				IDataTable results = Core.retrieveOQLDataTable(context, buildRequest(query, offset, PAGE_SIZE));

				if (offset == 0) {
					List<String> headers = results.getSchema()
						.getColumnSchemas()
						.stream()
						.map(IDataColumnSchema::getName)
						.collect(Collectors.toCollection(ArrayList::new));
					writer.writeRow(headers);
					writer.writeRow(Collections.nCopies(headers.size(), "-"));
				}

				writer.writeDataTable(results, getContext());

				if (results.getRowCount() != PAGE_SIZE) {
					break;
				}
				offset += PAGE_SIZE;
			}
			OQL.resetParameters();
		
			return os.toString();
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ExportOQLToMarkdown";
	}

	// BEGIN EXTRA CODE
	private IOQLTextGetRequest buildRequest(String statement, int offset, int pagesize) {
		IOQLTextGetRequest request = Core.createOQLTextGetRequest();
		request.setQuery(statement);

		IParameterMap parameterMap = request.createParameterMap();
		IRetrievalSchema schema = Core.createRetrievalSchema();
		schema.setAmount(pagesize);
		schema.setOffset(offset);
		request.setRetrievalSchema(schema);
		for (Entry<String, Object> entry : OQL.getNextParameters().entrySet()) {
			parameterMap.put(entry.getKey(), entry.getValue());
		}
		request.setParameters(parameterMap);
		return request;
	}
	// END EXTRA CODE
}
